require("before")
require("remaps")
require("customCommands")
require("autocommands")
require("lazyPackageManager")

-- NOTE: Plugin configs
require("pluginConfigs.nvimJavaConfig")
require("pluginConfigs.autotagConfig")
require("pluginConfigs.blanklineConfig")
require("pluginConfigs.nvimTreeConfig")
require("pluginConfigs.autoCloseConfig")
require("pluginConfigs.dapConfig")
require("pluginConfigs.dapuiConfig")
require("pluginConfigs.dapVirtualTextConfig")
require("pluginConfigs.hierarchyConfig")
require("pluginConfigs.oilConfig")
