preload = /run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-binary-black.png

wallpaper = HDMI-A-1,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-binary-black.png
wallpaper = DP-2,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-binary-black.png
wallpaper = DP-3,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-binary-black.png
wallpaper = DP-1,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-binary-black.png
