$mod = SUPER
$terminal = kitty
$launcher = $HOME/.config/hypr/scripts/toggle-launcher.sh
$browser = $HOME/.config/hypr/scripts/open-browser.sh

source = ./conf.d/monitors.conf
source = ./conf.d/autostart.conf
source = ./conf.d/appearance.conf
source = ./conf.d/input.conf
source = ./conf.d/keybinds.conf
