preload = /run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-nineish-dark-gray.png

wallpaper = HDMI-A-1,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-nineish-dark-gray.png
wallpaper = DP-2,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-nineish-dark-gray.png
wallpaper = DP-3,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-nineish-dark-gray.png
wallpaper = DP-1,/run/current-system/sw/share/backgrounds/nixos/nix-wallpaper-nineish-dark-gray.png
