[opener]
scribus = [
	{ run = 'scribus "$@"', desc = "Open with Scribus", orphan = true },
]
zathura = [
	{ run = 'zathura "$@"', desc = "Open with Zathura", orphan = true },
]

[[open.prepend_rules]]
name = "*.sla"
use = "scribus"

[[open.prepend_rules]]
mime = "application/pdf"
use = "zathura"
