exec-once = hyprpaper
exec-once = $HOME/.config/hypr/scripts/start-waybar.sh
exec-once = swaync -c $HOME/.config/hypr/swaync/config.json -s $HOME/.config/hypr/swaync/style.css
exec-once = swayosd-server
exec-once = hypridle
exec-once = hintsd
exec-once = playerctld daemon

env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GTK_THEME,Adwaita:dark
