bind = $mod, t, exec, $terminal
bindr = SUPER, SUPER_L, exec, $launcher
bindr = SUPER, SUPER_R, exec, $launcher
bind = $mod, b, exec, $browser
bind = $mod, i, exec, /run/media/c043/Drive/EPICODE/c043-scripts/nvim-anywhere.sh
bind = $mod, n, exec, swayosd-client --input-volume mute-toggle
bind = $mod, BackSpace, exec, hyprlock
bind = $mod, Escape, exec, hyprlock
bind = $mod, f, exec, hints
bind = $mod, q, killactive
bind = $mod SHIFT, E, exit
bindel = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindel = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindl = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
bindl = , XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle
bindl = , XF86AudioPlay, exec, playerctl --player=playerctld play-pause
bindl = , XF86AudioNext, exec, playerctl --player=playerctld next
bindl = , XF86AudioPrev, exec, playerctl --player=playerctld previous

bind = $mod, H, exec, ~/.config/hypr/scripts/movefocus-warp.sh l
bind = $mod, L, exec, ~/.config/hypr/scripts/movefocus-warp.sh r
bind = $mod, K, exec, ~/.config/hypr/scripts/movefocus-warp.sh u
bind = $mod, J, exec, ~/.config/hypr/scripts/movefocus-warp.sh d

bind = $mod, left, exec, ~/.config/hypr/scripts/movefocus-warp.sh l
bind = $mod, right, exec, ~/.config/hypr/scripts/movefocus-warp.sh r
bind = $mod, up, exec, ~/.config/hypr/scripts/movefocus-warp.sh u
bind = $mod, down, exec, ~/.config/hypr/scripts/movefocus-warp.sh d

bind = $mod SHIFT, H, exec, ~/.config/hypr/scripts/movewindow-warp.sh l movewindoworgroup
bind = $mod SHIFT, L, exec, ~/.config/hypr/scripts/movewindow-warp.sh r movewindoworgroup
bind = $mod SHIFT, K, exec, ~/.config/hypr/scripts/movewindow-warp.sh u movewindoworgroup
bind = $mod SHIFT, J, exec, ~/.config/hypr/scripts/movewindow-warp.sh d movewindoworgroup

bind = $mod SHIFT, left, exec, ~/.config/hypr/scripts/movewindow-warp.sh l movewindow
bind = $mod SHIFT, right, exec, ~/.config/hypr/scripts/movewindow-warp.sh r movewindow
bind = $mod SHIFT, up, exec, ~/.config/hypr/scripts/movewindow-warp.sh u movewindow
bind = $mod SHIFT, down, exec, ~/.config/hypr/scripts/movewindow-warp.sh d movewindow

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8

bind = $mod CTRL, L, workspace, m+1
bind = $mod CTRL, H, workspace, m-1
bind = $mod SHIFT CTRL, L, exec, ~/.config/hypr/scripts/dynamic-workspace.sh move-next
bind = $mod SHIFT CTRL, H, exec, ~/.config/hypr/scripts/dynamic-workspace.sh move-prev

bind = $mod ALT, H, focusmonitor, l
bind = $mod ALT, L, focusmonitor, r
bind = $mod ALT, K, focusmonitor, u
bind = $mod ALT, J, focusmonitor, d

bind = $mod ALT, left, focusmonitor, l
bind = $mod ALT, right, focusmonitor, r
bind = $mod ALT, up, focusmonitor, u
bind = $mod ALT, down, focusmonitor, d


bind = $mod, d, movetoworkspacesilent, special:minimized
bind = $mod CTRL, d, exec, ~/.config/hypr/scripts/restore-minimized.sh

bind = $mod, m, fullscreen
bind = $mod SHIFT, Space, togglefloating

bind = $mod, o, exec, hyprctl dispatch layoutmsg togglesplit
bind = $mod, s, togglegroup
bind = ALT CTRL, h, changegroupactive, b
bind = ALT CTRL, l, changegroupactive, f

bind = $mod CTRL, n, exec, swaync-client -d

bind = SHIFT ALT CTRL, R, exec, hyprshot -m region
